[build]
  # No build command needed for static files
  publish = "."
  
  # Environment variables for production
  [build.environment]
    NODE_VERSION = "18"

# JavaScript modules with correct MIME type
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

# JSON data files
[[headers]]
  for = "*.json"  
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Cache-Control = "public, max-age=86400"
    
# CSS files
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000"
    
# HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Security headers for all files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; connect-src 'self' https://*.supabase.co wss://*.supabase.co; img-src 'self' data: https:"

# Use modular version as default entry point
[[redirects]]
  from = "/"
  to = "/index-modular.html"
  status = 200
  force = true

# Alternative routes for modular version
[[redirects]]
  from = "/guide"
  to = "/index-modular.html"
  status = 200
  
[[redirects]]  
  from = "/app"
  to = "/index-modular.html"
  status = 200